Implemented Dialog System
moonwards1/Moonwards-Virtual-Moon pull request #506
Opened 2020-08-25 23:15 UTC by yaelatletl

Ready to test and merge

2020-09-03 17:07 UTC, Reousa commented
How can I test this? @yaelatletl

2020-09-03 18:36 UTC, yaelatletl commented
res://addons/joyeux_dialog_system/src/components/display/Dialog Display.tscn and play the scene, the test file it uses is res://test.mtalk

2020-09-08 17:56 UTC, Reousa commented
Hitting skip isn't functional 
![image](https://user-images.githubusercontent.com/18017673/92511159-3bccde00-f20d-11ea-86ac-b0618cd0edc1.png)

Otherwise, lgtm

2020-09-08 17:57 UTC, Reousa requested changes

2020-09-08 17:57 UTC, Reousa commented on addons/joyeux_dialog_system/src/components/display/Dialog Display.gd
> +
This function causes the game to crash

2020-09-09 23:22 UTC, yaelatletl commented on addons/joyeux_dialog_system/src/components/display/Dialog Display.gd
> +
latest comit 0b25130 solves this issue adding a yield

2020-09-11 18:43 UTC, Reousa approved these changes

2020-09-11 19:42 UTC, merged